Module backup review.
e-COSI/odoo-tools pull request #10
Opened 2017-03-31 11:54 UTC by Rotschadel

To do:
-zip option to export database dump and filestore snapshot in a compressed file.

2017-03-31 15:33 UTC, lionel-deglise requested changes
Déplacer les script de provisioning et le vagrantfile dans un répertoire dev pour ne pas le confondre avec les fichiers du module.
retirer le template rsnapshot.conf
renommer module_backup ent backup_odoo
déplacer .json dans /exemple
Retirer le code python commenter
Sortir le template rsnapshot du fichier python
Ne pas laisser le logging en DEBUG ou ajouter un paramètre 
La méthode generate_snapshot est trop longue ==> splitter , idem pour dump

2017-04-12 12:57 UTC, lionel-deglise requested changes
Super boulot globalement 👏 , quelque remarques avant de valider

Code commenté à supprimer

il manque un arg --version et l'usage --help
pour les arg court, il faux rester sur 1 seul lettre -P pas -PG

remplacer assert par un message erreur + usage
Des commentaire pour chaque fonction seraient les bienvenus

l'exécution ne doit pas être faite dans la constructeur mais sur un appel d'opération

Il reste en commentaire une référence nominative à ton poste dans le vagrantfile

2017-04-18 12:28 UTC, Rotschadel commented
La gestion de l'option --help est déjà présente par défaut quand on utilise le module python argparse.

2017-05-05 08:45 UTC, lionel-deglise approved these changes

2017-05-05 08:46 UTC, merged